# Generated by Django 5.2.2 on 2025-07-03 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0006_rename_total_amount_order_total_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='created_at',
            new_name='ordered_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
    ]
