# Generated by Django 5.2.2 on 2025-07-05 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0007_rename_created_at_order_ordered_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_taken',
            field=models.BooleanField(default=False),
        ),
    ]
