# Generated by Django 5.2.2 on 2025-07-05 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0008_order_is_taken'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
