# Generated by Django 5.2.2 on 2025-07-13 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0010_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
